apiVersion: v1
kind: Pod
metadata:
  labels:
    role: jenkins-agent
spec:
  containers:
  - name: trufflehog
    image: trufflesecurity/trufflehog:3.88.0
    command: ["cat"]
    
  - name: gitleaks
    image: zricethezav/gitleaks:v8.24.2
    command: ["cat"]

  - name: semgrep
    image: semgrep/semgrep:1.114.0
    command: ["cat"]

  - name: dependency-check
    image: owasp/dependency-check:12.1.0
    command: ["cat"]
    volumeMounts:
    - name: dc-cache
      mountPath: /usr/share/dependency-check/data

  - name: syft
    image: anchore/syft:v1.22.0
    command: ["/syft", "serve"]

  - name: grype
    image: anchore/grype:v0.114.0-alpine
    command: ["cat"]

  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    command: ["cat"]

  - name: trivy
    image: aquasec/trivy:0.61.0
    command: ["cat"]
    volumeMounts:
    - name: trivy-cache
      mountPath: /root/.cache/trivy 

  - name: zap
    image: ghcr.io/zaproxy/zaproxy:2.16.1
    command: ["cat"]

  volumes:
  - name: dc-cache
    persistentVolumeClaim:
      claimName: dependency-check-cache
  - name: trivy-cache
    persistentVolumeClaim:
      claimName: trivy-cache
